version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf

python:
  install:
    - method: pip
      path: .[dev]
