language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'pypy3'
install:
  - pip install .
script:
  - pip install coveralls
  - pip install pytest-timeout
  - coverage run -m pytest tests/common/
  - coveralls
notifications:
  slack: bayeso:FWBoHH9TMqjKUJWkZxCaTNVE
