# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test-python-3-6:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run:
          name: Run tests
          command: | 
            pip install -U pip setuptools
            pip install pytest
            pip install .
            pytest tests/common
  
  build-and-test-python-3-7:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: Run tests
          command: | 
            pip install -U pip setuptools
            pip install pytest
            pip install .
            pytest tests/common
  
  build-and-test-python-3-8:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: | 
            pip install -U pip setuptools
            pip install pytest
            pip install .
            pytest tests/common
  
  build-and-test-python-3-9:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Run tests
          command: | 
            pip install -U pip setuptools
            pip install pytest
            pip install .
            pytest tests/common

workflows:
  tests:
    jobs:
      - build-and-test-python-3-6
      - build-and-test-python-3-7
      - build-and-test-python-3-8
      - build-and-test-python-3-9
